[project]
name = "postpilot-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dixit", email = "dixitbuild@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "pandas>=3.0.6",
    "python-dotenv>=1.2.4",
]

[project.scripts]
postpilot-ai = "postpilot_ai:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
